name: CIValidation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CIValidation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Set up Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install dependencies
      run: |
        sudo apt-get install libxmlsec1-dev pkg-config
        pip install -r requirements.txt

    - name: Run python tests
      run: './scripts/runPythonTests.sh'

    - name: Run javascript tests
      run: './scripts/runNodejsTests.sh'
        
    - name: Run pylint
      run: './scripts/runPyLint.sh'
